development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Bort
  admin_email: adam@isshen.com
  site_description: Bort extended fucntionality with YUI and silk sprite fam fam fam
  site_keywords: Bort Yui famfamfam silk sprite
  site_owner: None
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://www.example.com
  site_name: Bort
  admin_email: bort@bort.com
